import { Project } from './types';

export const initialProjects: Project[] = [
  {
    id: 'proj_code_arena_01',
    title: 'Code Arena',
    slug: 'code-arena-static-analysis',
    description:
      'A tiered progression coding competition platform featuring real-time interactive problem solving, automated static code analysis, and sandboxed Docker containerized code evaluation (Final Year Project).',
    techStack: ['React', 'Node.js', 'Express.js', 'MongoDB', 'Docker', 'REST APIs'],
    imageUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://junaidkanwar.netlify.app/',
    githubUrl: 'https://github.com/Faraz-Ibrar/25-Nov-FYP.git',
    featured: true,
    status: 'published',
    order: 1,
    createdAt: '2024-09-01T10:00:00.000Z',
    updatedAt: '2026-09-10T11:00:00.000Z',
  },
  {
    id: 'proj_game_craft_02',
    title: 'Game Craft',
    slug: 'game-craft-pc-store',
    description:
      'High-performance gaming PC components marketplace built on MongoDB, Express.js, React, and Node.js. Features technical hardware spec comparisons, parametric multi-attribute filtering, shopping cart persistence, and vendor inventory management.',
    techStack: ['React', 'Node.js', 'Express.js', 'MongoDB', 'Tailwind CSS', 'REST APIs'],
    imageUrl: 'https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://junaidkanwar.netlify.app/',
    githubUrl: 'https://github.com/baymx04-ux/Game-Craft.git',
    featured: false,
    status: 'published',
    order: 2,
    createdAt: '2024-06-15T12:00:00.000Z',
    updatedAt: '2026-09-05T14:30:00.000Z',
  },
  {
    id: 'proj_home_cook_03',
    title: 'Home Cook',
    slug: 'home-cook-delivery',
    description:
      'Artisanal homemade food delivery application empowering home chefs. Features chef portfolio profiles, dynamic daily menu scheduling, live order state machine, and simulated transaction gateway.',
    techStack: ['React', 'Node.js', 'Express.js', 'MongoDB', 'REST APIs', 'Postman'],
    imageUrl: 'https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://junaidkanwar.netlify.app/',
    githubUrl: 'https://github.com/baymx04-ux/Home-Cook.git',
    featured: false,
    status: 'published',
    order: 3,
    createdAt: '2024-03-20T08:00:00.000Z',
    updatedAt: '2026-08-28T09:15:00.000Z',
  },
  {
    id: 'proj_2j_blogs_04',
    title: '2J Blogs',
    slug: '2j-blogs-blazor',
    description:
      'Responsive editorial blogging engine built with Blazor .NET and Microsoft SQL Server. Implements secure cookie session authentication, markdown document composing, categorization, and mobile-first typography.',
    techStack: ['Blazor', '.NET Core', 'C#', 'Microsoft SQL Server', 'Bootstrap'],
    imageUrl: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80',
    liveUrl: 'https://junaidkanwar.netlify.app/',
    githubUrl: 'https://github.com/baymx04-ux/2J-Blogs.git',
    featured: false,
    status: 'published',
    order: 4,
    createdAt: '2023-11-10T16:00:00.000Z',
    updatedAt: '2026-08-10T18:00:00.000Z',
  },
];
