import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#F1F2EC",
        surface: "#E9EBE3",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff5f0",
        "surface-container": "#e9efea",
        "surface-container-high": "#e4eae4",
        "surface-container-highest": "#dee4df",
        "surface-bright": "#f5fbf5",
        "surface-dim": "#d5dcd6",
        ink: "#171D1A",
        "ink-muted": "#5B645E",
        pine: "#2B6455",
        primary: "#0d4c3e",
        "primary-container": "#2b6455",
        "on-primary": "#ffffff",
        copper: "#B8622F",
        secondary: "#964817",
        "secondary-container": "#fe9a62",
        "secondary-fixed": "#ffdbca",
        "on-secondary-fixed": "#331100",
        border: "#DBDED3",
        outline: "#707975",
        "outline-variant": "#bfc9c4",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-6": "24px",
        "space-8": "32px",
        "space-12": "48px",
        "space-16": "64px",
        "space-24": "96px",
        gutter: "24px",
        "max-width": "1200px",
      },
      fontFamily: {
        display: ["Newsreader", "Fraunces", "serif"],
        "headline-lg": ["Newsreader", "Fraunces", "serif"],
        "headline-md": ["Newsreader", "Fraunces", "serif"],
        "headline-sm": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "code-md": ["Space Mono", "IBM Plex Mono", "monospace"],
        "code-sm": ["Space Mono", "IBM Plex Mono", "monospace"],
      },
      fontSize: {
        display: ["64px", { lineHeight: "1.05", letterSpacing: "-0.5px", fontWeight: "500" }],
        "headline-lg": ["44px", { lineHeight: "1.15", letterSpacing: "-0.25px", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-sm": ["22px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["19px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["17px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-md": ["15px", { lineHeight: "1.4", fontWeight: "500" }],
        "code-md": ["13px", { lineHeight: "1.4", letterSpacing: "0.2px", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "1.4", letterSpacing: "0.2px", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "2px",
        sm: "2px",
        md: "4px",
        lg: "8px",
      },
    },
  },
  plugins: [],
};

export default config;
