import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#F6F7F4",
        surface: "#FFFFFF",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#F1F4F0",
        "surface-container": "#EAEEE9",
        "surface-container-high": "#E3E8E2",
        "surface-container-highest": "#DDE2DC",
        "surface-bright": "#F2F9F3",
        "surface-dim": "#DBDEDA",
        ink: "#0D130E",
        "ink-muted": "#5D6660",
        pine: "#0E7A4D",
        primary: "#0A5F3B",
        "primary-container": "#0E7A4D",
        "on-primary": "#FFFFFF",
        accent: "#BEF264",
        copper: "#C04314",
        secondary: "#A34A1A",
        "secondary-container": "#FEA26E",
        "secondary-fixed": "#FFDCC8",
        "on-secondary-fixed": "#2B1204",
        border: "#E6E8E2",
        outline: "#737B74",
        "outline-variant": "#C8CFC8",
        error: "#DC2828",
        "error-container": "#FFDAD6",
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-6": "24px",
        "space-8": "32px",
        "space-12": "48px",
        "space-16": "64px",
        "space-24": "96px",
        gutter: "24px",
        "max-width": "1200px",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "code-md": ["Space Mono", "IBM Plex Mono", "monospace"],
        "code-sm": ["Space Mono", "IBM Plex Mono", "monospace"],
      },
      fontSize: {
        display: ["72px", { lineHeight: "1.04", letterSpacing: "-2.5px", fontWeight: "600" }],
        "headline-lg": ["44px", { lineHeight: "1.12", letterSpacing: "-1px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "1.25", letterSpacing: "-0.4px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["19px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-md": ["17px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-sm": ["15px", { lineHeight: "1.55", fontWeight: "400" }],
        "label-md": ["15px", { lineHeight: "1.4", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "1.45", letterSpacing: "0.2px", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "1.45", letterSpacing: "0.2px", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "10px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(16,24,40,0.04), 0 6px 16px -6px rgba(16,24,40,0.10)",
        "card-lg": "0 2px 4px rgba(16,24,40,0.04), 0 12px 32px -8px rgba(16,24,40,0.12)",
        glow: "0 0 0 1px rgba(14,122,77,0.15), 0 8px 24px -8px rgba(14,122,77,0.25)",
      },
    },
  },
  plugins: [],
};

export default config;
