import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "#0F1115",
        surface: "#171A21",
        "surface-container-lowest": "#FFFFFF",
        "surface-container-low": "#1D212A",
        "surface-container": "#232833",
        "surface-container-high": "#2A303C",
        "surface-container-highest": "#323946",
        "surface-bright": "#414A59",
        "surface-dim": "#13161B",
        ink: "#F2F4F7",
        "ink-muted": "#9AA4B1",
        pine: "#D9A62E",
        primary: "#C08F18",
        "primary-container": "#D9A62E",
        "on-primary": "#0A0B0D",
        accent: "#F2B84B",
        copper: "#E8A33D",
        secondary: "#C98529",
        "secondary-container": "#F5C56E",
        "secondary-fixed": "#FFE1B5",
        "on-secondary-fixed": "#3A2700",
        border: "#262C37",
        outline: "#8A94A3",
        "outline-variant": "#4A5261",
        error: "#F87171",
        "error-container": "#3B1215",
      },
      spacing: {
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-6": "24px",
        "space-8": "32px",
        "space-12": "48px",
        "space-16": "64px",
        "space-24": "96px",
        gutter: "24px",
        "max-width": "1200px",
      },
      fontFamily: {
        display: ["Space Grotesk", "sans-serif"],
        "headline-lg": ["Space Grotesk", "sans-serif"],
        "headline-md": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Grotesk", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-md": ["IBM Plex Sans", "sans-serif"],
        "code-md": ["Space Mono", "IBM Plex Mono", "monospace"],
        "code-sm": ["Space Mono", "IBM Plex Mono", "monospace"],
      },
      fontSize: {
        display: ["72px", { lineHeight: "1.04", letterSpacing: "-2.5px", fontWeight: "600" }],
        "headline-lg": ["44px", { lineHeight: "1.12", letterSpacing: "-1px", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "1.25", letterSpacing: "-0.4px", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["19px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-md": ["17px", { lineHeight: "1.65", fontWeight: "400" }],
        "body-sm": ["15px", { lineHeight: "1.55", fontWeight: "400" }],
        "label-md": ["15px", { lineHeight: "1.4", fontWeight: "600" }],
        "code-md": ["13px", { lineHeight: "1.45", letterSpacing: "0.2px", fontWeight: "500" }],
        "code-sm": ["11px", { lineHeight: "1.45", letterSpacing: "0.2px", fontWeight: "500" }],
      },
      borderRadius: {
        DEFAULT: "10px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(0,0,0,0.2), 0 6px 16px -6px rgba(0,0,0,0.4)",
        "card-lg": "0 2px 4px rgba(0,0,0,0.22), 0 12px 32px -8px rgba(0,0,0,0.45)",
        glow: "0 0 0 1px rgba(217,166,46,0.18), 0 8px 24px -8px rgba(217,166,46,0.28)",
      },
    },
  },
  plugins: [],
};

export default config;
